###############################################################################
### Project: Gitlab - community edition
###############################################################################

---

- name: Wait for GitLab CE to be healthy
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/gitlab/-/health"
    validate_certs: false
  register: result
  until: result.status == 200
  retries: 300
  delay: 5
  tags:
    - post_run

- name: Check if Gitlab Runner already has config
  ansible.builtin.stat:
    path: "/home/{{ ansible_user }}/container-projects/{{ containerhost__container_project_name }}/gitlab-runner/config/config.toml"
  register: containerhost__gitlab_ce_runner_config_file
  tags:
    - post_run

- name: Register Gitlab Runner in a container 
  when: not containerhost__gitlab_ce_runner_config_file.stat.exists
  tags:
    - post_run
  block:
    - name: Create or Update Admin API Token
      ansible.builtin.shell:
        cmd: >
          podman exec gitlab_ce_gitlab-ce_1 gitlab-rails runner "
          user = User.find_by_username('root');
          token_name = 'Ansible_Admin_Token';
          token = user.personal_access_tokens.find_by(name: token_name) || user.personal_access_tokens.create(name: token_name, scopes: [:api]);
          token.set_token('glpat-AnsibleAdminProvisioningToken01');
          token.expires_at = 1.days.from_now;
          token.save!;
          print token.token"
      register: token_generation
      changed_when: true
      tags:
        - post_run

    - name: Set gitlab_admin_api_token fact
      ansible.builtin.set_fact:
        gitlab_admin_api_token: "{{ token_generation.stdout | trim }}"
      tags:
        - post_run

    - name: Create Instance Runner via API
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}/gitlab/api/v4/user/runners"
        method: POST
        status_code: 201
        validate_certs: false
        headers:
          PRIVATE-TOKEN: "{{ gitlab_admin_api_token | trim }}"
        body_format: json
        body:
          runner_type: "instance_type"
          description: "Runner in a container on {{ ansible_host }}"
          tag_list:
            - podman
            - shell
          run_untagged: true
      register: runner_reg_info
      tags:
        - post_run

    - name: Store Runner Authentication Token
      ansible.builtin.set_fact:
        runner_auth_token: "{{ runner_reg_info.json.token }}"
      tags:
        - post_run

    - name: Register GitLab Runner
      ansible.builtin.shell:
        cmd: >
          podman exec gitlab_ce_gitlab-runner_1
          gitlab-runner register
          --non-interactive
          --url "http://gitlab_ce_gitlab-ce_1:9999/gitlab"
          --token "{{ runner_auth_token }}"
          --executor "shell"
      args:
        creates: "/home/{{ ansible_user }}/container-projects/{{ containerhost__container_project_name }}/gitlab-runner/config/config.toml"
      tags:
        - post_run

- name: Get initial root password
  ansible.builtin.shell:
    cmd: >
      podman exec gitlab_ce_gitlab-ce_1 cat /etc/gitlab/initial_root_password
  register: containerhost__gitlab_initial_root_password
  tags:
    - post_run

- name: Show initial root password
  ansible.builtin.debug:
    var: containerhost__gitlab_initial_root_password
  tags:
    - post_run
