[commands]
#  What kind of upgrade to perform:
# default                            = all available upgrades
# security                           = only the security upgrades
upgrade_type = default
random_sleep = 0

network_online_timeout = 60
download_updates = yes
apply_updates = yes
reboot = never

[emitters]

# How to send messages.  Valid options are stdio, email and motd.  If
# emit_via includes stdio, messages will be sent to stdout
# If emit_via includes motd, /etc/motd file will have the messages.
emit_via = stdio, motd

[base]
# This section overrides dnf.conf

# Use this to filter DNF core messages
debuglevel = 1
